### ISSUE TITLE
Add product to cart as well as on Supabase [One to Many relationship]

### ISSUE THREAD

**Issue by Venkatknight2295** [pooranjoyb/popShop#109]
### Tasks : 

- [ ] Create a Table in Supabase called Cart. It should have the field called username and product. 
- [ ] Now products should be an `Array of Objects` and each Product will be having the following fields.
- [ ] Price, Item name, description, quantity and ratings
- [ ] Add to cart should add that in the Cart Table.

#### Note : No need to update the Carts page. We'll do that in a separate issue.

@Venkatknight2295

**Comment by pooranjoyb** [comment]
Congratulations, @Venkatknight2295! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Added to the waitlist. Will work upon it sooner. @Venkatknight2295

**Comment by amanjaiswal7236** [comment]
Can I work on this issue??

**Comment by pooranjoyb** [comment]
just wait until we finish up the ui part :)
Till then you can go ahead with other issues. Happy coding :)
@amanjaiswal7236

**Comment by pooranjoyb** [comment]
@Venkatknight2295 @amanjaiswal7236 You guys wanna continue this?

**Comment by Venkatknight2295** [comment]
@pooranjoyb i am ready

**Comment by pooranjoyb** [comment]
Go ahead @Venkatknight2295 🚀 
Drop me your email here in comments to get access to Supabase Organization.

**Comment by Venkatknight2295** [comment]
coding2295@gmail.com

**Comment by Venkatknight2295** [comment]
My work is to add products to cart and increase price when quantity is increased in cart right??

**Comment by Venkatknight2295** [comment]
Please after i make pr lable it and merge as soon as possible

**Comment by Mahitej28** [comment]
@Venkatknight2295 updates??

**Comment by pooranjoyb** [comment]
> My work is to add products to cart and increase price when quantity is increased in cart right??

![image](https://github.com/pooranjoyb/popShop/assets/90945182/7921a1eb-8dfd-44f3-8233-05e85a894727)

Added to team. Please check mail and the Tasks mentioned above. @Venkatknight2295

**Comment by Venkatknight2295** [comment]
sorry i am not able to understand supabase properly to work on this So please assign this task to some one else

**Comment by amanjaiswal7236** [comment]
Can I work on this issue??

**Comment by pooranjoyb** [comment]
go ahead. Drop your mail here for supabase access. @amanjaiswal7236

**Comment by dhruv8433** [comment]
@pooranjoyb 

i completed supabase and everything is working
please add me in team so i can create `cart` table in supabase

**Comment by pooranjoyb** [comment]
Please drop you email here in comments @dhruv8433

**Comment by dhruv8433** [comment]
dhruvrsoni04@gmail.com

**Comment by pooranjoyb** [comment]
> [dhruvrsoni04@gmail.com](mailto:dhruvrsoni04@gmail.com)

check mail

**Comment by amanjaiswal7236** [comment]
Hey, is this issue already solved??

**Comment by pooranjoyb** [comment]
Hii @amanjaiswal7236 As of now @dhruv8433 is working on this. He's facing some build errors and some redux functions has to be setup. Let's wait for him till tom EOD, else will assign you.
