### ISSUE TITLE
Filter feature on the products page

### ISSUE THREAD

**Issue by Niharika0104** [pooranjoyb/popShop#12]
### Tasks :

- [ ] Define the criteria by which users can filter products (e.g., price range, category, brand).
- [ ] The modal should popup upon clicking the `Filter icon`. 
- [ ] Use `<IoFilterCircleOutline />` from `react-icons`
- [ ] Use the responsive modal from [here](https://daisyui.com/components/modal)

**Comment by pooranjoyb** [comment]
Go for it @Niharika0104 🚀
