### ISSUE TITLE
Folder Structuring & Minor Bugs.

### ISSUE THREAD

**Issue by sristy17** [pooranjoyb/popShop#135]
### File Name

TopButton.tsx

### Reason for Refactoring the Code

Many folder Structuring and Minor Bugs to be fixed.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

**Comment by pooranjoyb** [comment]
Congratulations, @sristy17! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Okay, take these tasks and finish 'em up!

### Tasks : 

 - [ ] Create a `Folder` for `Topbutton` similar to `Loader` and refactor the imports wherever necessary for `TopButton.tsx.
 - [ ] `Scroll to TopButton` doesn't math the theme. Use any one `#06D6A0` ,  `#EF476F`, `#FFD166`
 - [ ] Fix the routing for `Cart` in the Footer. currently its `/home/cart`. Make it `/home/shop/cart` (Update the Link in Footer)
 - [ ] Remove the `Order Summary` container from the `Cart` page. Make sure that the product table takes up its width after removing it.
 - [ ] Add the `shadow-2xl or shadow-xl` and a `border-2` property to the `Cart Modal` . Seems like border's invisible :/
![image](https://github.com/pooranjoyb/popShop/assets/90945182/ba506139-e631-44c3-b9be-276f5f233586)
 - [ ] Remove `Settings` and add `Shop` &  `Cart` along with it's routing. 
![image](https://github.com/pooranjoyb/popShop/assets/90945182/175caddd-5e69-4736-bb47-3bd9e886489a)
- [ ] Create a `Cancel` button that closes the Modal in Product Filters.
![image](https://github.com/pooranjoyb/popShop/assets/90945182/e8b8e0e4-d864-4e00-b386-f7ffa1fa2c32)


For any queries drop it right in the comments! 🚀 
All the best 💯 @sristy17

**Comment by pooranjoyb** [comment]
Also add the `hide/show` icon for the password :) @sristy17 
![image](https://github.com/pooranjoyb/popShop/assets/90945182/d9ecbfac-100b-4d6a-911a-0621332acf4d)
