### ISSUE TITLE
[Feature] Add more fields to `Auth/Signup`

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#148]
### Description

As of now we are saving only `username`, `email`, and `password` to the Supabase table. Hence we need to save more data to reflect them back in the `User Profile`

### Tasks
- [ ] Update the `SignUpSchema` in `utils/schema.ts` with the remaining fields
   - FirstName
   - LastName
   - Gender
   - Phone 
   - Address
   - Account Creation Date (Use `new Date();`)

### Screenshots

_The following is the supabase table you'd need to work upon. The column names can be found in the Screenshot below._

![image](https://github.com/pooranjoyb/popShop/assets/90945182/a5945f6d-b197-4d2f-b455-6f04c1f427a6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by me-shweta** [comment]
@pooranjoyb Hi! I don't have any experience in this field, it's my first time contributing to a code issue. However, I'm willing to give it a try. If you could help me with some doubts, I'd be able to proceed with this issue.

**Comment by pooranjoyb** [comment]
Go ahead! @me-shweta 🚀

**Comment by sristy17** [comment]
Can you please assign me this, I have the code ready!

**Comment by me-shweta** [comment]
Hi @pooranjoyb,
As part of the recent updates to your authentication system, I've added new fields to the user profile such as first name, last name, gender, phone, address, and account creation date. To ensure that this information is properly stored and accessible, I'd like to confirm where the Supabase table for user profiles is located and who manages its schema. If the table needs to be updated to include these new fields, please let me know the process for making those changes.

**Comment by pooranjoyb** [comment]
> Hi @pooranjoyb, As part of the recent updates to your authentication system, I've added new fields to the user profile such as first name, last name, gender, phone, address, and account creation date. To ensure that this information is properly stored and accessible, I'd like to confirm where the Supabase table for user profiles is located and who manages its schema. If the table needs to be updated to include these new fields, please let me know the process for making those changes.

Drop me your email. I'll give you supabase access 👍🏼

**Comment by me-shweta** [comment]
done!

**Comment by pooranjoyb** [comment]
> done!

Please mention it here in the comments :) @me-shweta

**Comment by me-shweta** [comment]
shwetameena0511@gmail.com @pooranjoyb (:

**Comment by pooranjoyb** [comment]
> [shwetameena0511@gmail.com](mailto:shwetameena0511@gmail.com)

![image](https://github.com/pooranjoyb/popShop/assets/90945182/7e329079-7b98-4f4b-b7ad-edc7cfec6c49)

**Comment by pooranjoyb** [comment]
What's the update @me-shweta ?

**Comment by me-shweta** [comment]
Hi @pooranjoyb,

**Tasks Completed**
- Updated SignUpSchema in utils/schema.ts
- Updated Auth.tsx File

While I have successfully updated the schema and the form, I am currently facing challenges with saving the new data to Supabase during the signup process.

**Comment by pooranjoyb** [comment]
What are the challenged. Check the response that you receive after hitting the API. That'll help you to identify the issue :) @me-shweta

**Comment by me-shweta** [comment]
@pooranjoyb I need your help regarding GGSOC. I have many successful PRs, and you merged one as well, but my name is still not on the leaderboard. I'm wondering why this happened. Can you help me with this?

**Comment by sristy17** [comment]
> @sristy17 Do you wanna continue with the remaining part?
> we can split this issue in 2 parts.
> 
> - @me-shweta raises a PR for `task1`
> - @sristy17 can finish up `task2` and also fetch the logged-in `UserData` and render them in Profile.
> 
> Sounds Good? @me-shweta @sristy17 

Yes.

**Comment by pooranjoyb** [comment]
Okay then @me-shweta create a PR for this issue. We'll review and merge if everything's alright. Meanwhile I'm creating another issue for @sristy17 that's dependent on this issue. 

Please drop a PR by today itself @me-shweta

**Comment by me-shweta** [comment]
sure!

**Comment by me-shweta** [comment]
@pooranjoyb I've performed the pull request. Please review and let me know if there are any issues. There have been some recent changes in the last 1-2 days, so conflicts may arise since the fork was created. If any conflicts occur, feel free to notify me. :)
