### ISSUE TITLE
[Feature] Save `UserData` w.r.t New Schema and render them in Profile. 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#158]
### Tasks 

- [ ] Save all these data to Supabase on Signup.
- [ ] Fetch the Logged in User Details from the table and render them in the profile.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
@sristy17 Raise a PR for this issue when #148 is merged.

**Comment by sristy17** [comment]
Okay.

**Comment by pooranjoyb** [comment]
Done https://github.com/pooranjoyb/popShop/commit/7f3667b6340ad5f029f5374bcef20fdeb9fbb219
You can continue with the `signup` @sristy17

**Comment by sristy17** [comment]
okay
