### ISSUE TITLE
[Feature] Creating contact us page.

### ISSUE THREAD

**Issue by yashi-15** [pooranjoyb/popShop#165]
### Description

- To create a "Contact Us" page that complements the overall theme and styling of your website.
- I will ensure the design is cohesive with your website's color scheme, typography, and layout to maintain brand consistency.
- The link to the contact us page will be provided in the footer.

I want to work on this issue kindly assign it to me under GSSOC'24.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @yashi-15! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
One issue at a time @yashi-15 
Let's start with #163

**Comment by gdhyani** [comment]
I can work on this.

**Comment by pooranjoyb** [comment]
@gdhyani 

Okay do one thing. Create a single PR that closes both #165 and #174 
I'll add `level3` to it. 

### TODO  :

- Maintain the Folder Structure of the Project.
- Use Components like `Navbar`, `Footer` if necessary.
- `Contact Us` page must maintain the theme of the Popshop.
- Make is as Minimalist as possible. 
- `Contact Us` page should have only `Name`, `Email`, `Message` with a `Send` button.

**Comment by gdhyani** [comment]
> @gdhyani
> 
> Okay do one thing. Create a single PR that closes both #165 and #174 I'll add `level3` to it.
> 
> ### TODO :
> * Maintain the Folder Structure of the Project.
> * Use Components like `Navbar`, `Footer` if necessary.
> * `Contact Us` page must maintain the theme of the Popshop.
> * Make is as Minimalist as possible.
> * `Contact Us` page should have only `Name`, `Email`, `Message` with a `Send` button.

Done with all the changes. Created a Pull Request #176.
