### ISSUE TITLE
[BUG] Minor UI + Utility bugs

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#236]
### Tasks
- [ ] Add skeleton-loader in `Our Store`
- [ ] Update the Cart Model with real-data.

![image](https://github.com/pooranjoyb/popShop/assets/90945182/1b856265-6392-44a1-b8f1-d83058224651)
- [ ] We don't need the **Table header** and **Apply Coupon section** when cart is empty.

![image](https://github.com/pooranjoyb/popShop/assets/90945182/0cdda6db-4e85-49f4-b7b3-81b1f692f5ff)
- [ ] Remove this `Contact Us` from here and directly route it through the `Contact` in `Navbar`

![image](https://github.com/pooranjoyb/popShop/assets/90945182/5ac98198-16cb-4633-b4cd-7479396151fb)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by SandipGyawali** [comment]
@pooranjoyb can i look at it 
??

**Comment by pooranjoyb** [comment]
Yes go ahead :) 🚀 @SandipGyawali

**Comment by SandipGyawali** [comment]
[Screencast from 2024-06-17 15-11-08.webm](https://github.com/pooranjoyb/popShop/assets/66510112/9f81ac46-8f0f-47be-9fa9-025268059048)


@pooranjoyb what's your view on the skeleton ??

**Comment by pooranjoyb** [comment]
> @pooranjoyb what's your view on the skeleton ??

Sahi hai :)
